/** Gateway client SATRIA SISWA. Token hanya dipakai server-side. */
function gatewayConfig_(){const key='SM_GATEWAY_CONFIG_V1',cache=CacheService.getScriptCache();try{const hit=cache.get(key);if(hit){const c=JSON.parse(hit);if(c&&c.url&&c.token)return c}}catch(e){}const p=PropertiesService.getScriptProperties(),c={url:String(p.getProperty(APP_CONFIG.PROP.GATEWAY_URL)||'').trim(),token:String(p.getProperty(APP_CONFIG.PROP.GATEWAY_TOKEN)||'').trim()};if(!c.url||!c.token)throw new Error('Gateway belum dikonfigurasi OWNER.');try{cache.put(key,JSON.stringify(c),300)}catch(e){}return c}
function clearGatewayConfigCache_(){try{CacheService.getScriptCache().remove('SM_GATEWAY_CONFIG_V1')}catch(e){}}
function gatewayCall_(action,payload){const c=gatewayConfig_(),body=Object.assign({},payload||{},{action,token:c.token}),res=UrlFetchApp.fetch(c.url,{method:'post',contentType:'application/json',payload:JSON.stringify(body),muteHttpExceptions:true,followRedirects:true}),status=res.getResponseCode(),text=res.getContentText();let data;try{data=JSON.parse(text||'')}catch(e){throw new Error('Gateway mengembalikan respons bukan JSON. HTTP '+status)}if(!data||data.ok!==true)throw new Error((data&&data.message)||('Gateway menolak operasi. HTTP '+status));return data}
function gatewayReadClass_(spreadsheetId,sheet){return gatewayCall_('SPREADSHEET_READ',{spreadsheetId,sheet})}
function gatewayAppendClass_(spreadsheetId,sheet,row){return gatewayCall_('SPREADSHEET_APPEND',{spreadsheetId,sheet,row})}
function gatewayDeleteClass_(spreadsheetId,sheet,rowNumber){return gatewayCall_('SPREADSHEET_DELETE_ROW',{spreadsheetId,sheet,rowNumber})}
function gatewayEnsureSheet_(spreadsheetId,sheet,headers){return gatewayCall_('ENSURE_SHEET',{spreadsheetId,sheet,headers})}
function gatewayEnsureHeaders_(spreadsheetId,sheet,headers){return gatewayCall_('ENSURE_HEADERS',{spreadsheetId,sheet,headers})}
function gatewayGetMasterReference_(masterId){return gatewayCall_('GET_MASTER_REFERENCE',{spreadsheetId:masterId})}
