/** SATRIA MUDA — konfigurasi aplikasi. */
const APP_CONFIG = Object.freeze({
  NAME:'SIM SATRIA MUDA', VERSION:'1.2.0', TIMEZONE:'Asia/Jakarta', OWNER_EMAIL:'yazid.mubasir12@admin.sma.belajar.id',
  PROP:{MASTER_SIM_ID:'MASTER_SIM_ID',GATEWAY_URL:'GATEWAY_URL',GATEWAY_TOKEN:'GATEWAY_TOKEN',SETUP_OWNER_EMAIL:'SETUP_OWNER_EMAIL'},
  ROLE:{OWNER:'OWNER',ADMIN_KELAS:'ADMIN_KELAS',SISWA:'SISWA',PETUGAS_SOAL:'PETUGAS_SOAL'},
  SHEET:{MASTER_SIM:'MASTER_SIM',MASTER_KELAS:'MASTER_KELAS',MASTER_MODUL:'MASTER_MODUL',MASTER_PETUGAS_SOAL:'MASTER_PETUGAS_SOAL',BANK_SOAL:'BANK_SOAL',USERS:'USERS',KELAS:'KELAS',AGENDA_BELAJAR:'TRX_AGENDA_BELAJAR',LATIHAN_SOAL:'TRX_LATIHAN_SOAL'}
});
