/** SATRIA MUDA — Dashboard aktivitas lintas kelas. OWNER dan ADMIN_KELAS dapat melihat ringkasan seluruh kelas. */
function getDashboardData(){const session=getSessionInfo();dashboardAssertViewer_(session);const kelas=listKelas_();const cards=Object.keys(SISWA_MODULES).map(function(kode){const cfg=SISWA_MODULES[kode],all=kode==='BELAJAR_MANDIRI'?getLearningDashboardRows_(kelas):getDashboardAllRows_(kode,kelas),kelasSet={};all.forEach(function(r){kelasSet[String(r.idKelas||r.namaKelas||'-')]=true;});return{kode,nama:cfg.nama,icon:cfg.icon,total:all.length,kelasCount:Object.keys(kelasSet).length,rows:all.slice(0,6)};});return{ok:true,scope:'ALL_CLASSES',role:session.role,kelasCount:kelas.length,updatedAt:new Date(),cards};}
function getDashboardModuleData(kode){const session=getSessionInfo();dashboardAssertViewer_(session);requireModule_(kode);const rows=kode==='BELAJAR_MANDIRI'?getLearningDashboardRows_(listKelas_()):getDashboardAllRows_(kode,listKelas_());return{ok:true,kode,role:session.role,total:rows.length,rows:rows.slice(0,300),updatedAt:new Date()};}
function dashboardAssertViewer_(session){const allowed=[APP_CONFIG.ROLE.OWNER,APP_CONFIG.ROLE.ADMIN_KELAS];if(!session||allowed.indexOf(session.role)<0)throw new Error('Dashboard hanya dapat diakses oleh OWNER atau ADMIN_KELAS.');}
function getLearningDashboardRows_(kelas){const all=[];(kelas||[]).forEach(function(k){try{const r=gatewayReadClass_(k.spreadsheetId,APP_CONFIG.SHEET.LATIHAN_SOAL),data=r&&r.data?r.data:{},rows=Array.isArray(data.rows)?data.rows:[],h=Array.isArray(data.headers)?data.headers:LM_PROGRESS_HEADERS;rows.forEach(function(x){const o={id:x[0],timestamp:x[1],email:x[2],nisn:x[3],nama:x[4],idKelas:x[5],idSoal:x[6],jenis:x[7],level:x[8],jawaban:x[9],benar:x[10],skor:x[11],xp:x[12],durasiDetik:x[13],namaKelas:k.namaKelas||k.idKelas};all.push(o);});}catch(e){}});all.sort(function(a,b){return dashboardDateValue_(b.timestamp)-dashboardDateValue_(a.timestamp);});return all;}
function getDashboardAllRows_(kode,kelas){const cfg=requireModule_(kode),all=[];(kelas||[]).forEach(function(k){try{const result=gatewayReadClass_(k.spreadsheetId,cfg.sheet),data=result&&result.data?result.data:{},rows=Array.isArray(data.rows)?data.rows:(Array.isArray(data.values)?data.values:[]),headers=Array.isArray(data.headers)?data.headers:null;rows.forEach(function(row){const item=dashboardRowToObject_(cfg,row,headers);item.idKelas=item.idKelas||k.idKelas;item.namaKelas=k.namaKelas||k.idKelas;all.push(item);});}catch(e){}});all.sort(function(a,b){return dashboardDateValue_(b.tanggal||b.timestamp)-dashboardDateValue_(a.tanggal||a.timestamp);});return all;}
function dashboardRowToObject_(cfg,row,headers){if(row&&!Array.isArray(row)&&typeof row==='object'){const direct={};Object.keys(row).forEach(function(k){const key=dashboardNormalizeKey_(k);if(key)direct[key]=row[k];});return direct;}const o={},safeHeaders=Array.isArray(headers)&&headers.length?headers:moduleHeaders_(cfg);safeHeaders.forEach(function(h,i){const key=dashboardNormalizeKey_(h);if(key)o[key]=row[i];});if(o.id===undefined)o.id=row[0];if(o.timestamp===undefined)o.timestamp=row[1];if(o.email===undefined)o.email=row[2];if(o.nisn===undefined)o.nisn=row[3];if(o.nama===undefined)o.nama=row[4];if(o.idKelas===undefined)o.idKelas=row[5];cfg.fields.forEach(function(f,i){if(o[f[0]]===undefined)o[f[0]]=row[6+i];});return o;}
function dashboardNormalizeKey_(header){const s=String(header||'').trim();if(!s)return '';const aliases={'id_kelas':'idKelas','idkelas':'idKelas','nama_guru':'namaGuru','nama guru':'namaGuru','mata_pelajaran':'mataPelajaran','mata pelajaran':'mataPelajaran','tujuan_belajar':'tujuanBelajar','tujuan belajar':'tujuanBelajar','kegiatan_belajar':'kegiatan','kegiatan belajar':'kegiatan','nilai/karakter yang dipraktikkan':'nilaiKarakter','nilai_karakter':'nilaiKarakter','hal_dipelajari':'halDipelajari','hal yang dipelajari':'halDipelajari','nama_prestasi':'namaPrestasi','nama prestasi':'namaPrestasi','sumber_belajar':'sumberBelajar','sumber belajar':'sumberBelajar','hasil_belajar':'hasilBelajar','hasil belajar':'hasilBelajar','nama_kegiatan':'namaKegiatan','nama kegiatan':'namaKegiatan'};const low=s.toLowerCase();if(aliases[low])return aliases[low];return s.replace(/[^a-zA-Z0-9]+(.)/g,function(_,c){return c.toUpperCase();}).replace(/^[A-Z]/,function(c){return c.toLowerCase();});}
function dashboardDateValue_(v){if(v instanceof Date)return v.getTime();const d=new Date(v);return isNaN(d.getTime())?0:d.getTime();}
