/** SATRIA MUDA V1 — Learning Challenge Engine: bank soal + progres siswa. */
const LM_TYPES=Object.freeze({LITERASI:'LITERASI',NUMERASI:'NUMERASI'});
const LM_LEVELS=[1,2,3,4,5];
const LM_BANK_HEADERS=['id_soal','jenis','level','target_kelas','materi','indikator','stimulus','pertanyaan','tipe_soal','opsi_a','opsi_b','opsi_c','opsi_d','jawaban','pembahasan','pembuat_email','pembuat_nama','status','created_at','updated_at'];
const LM_PROGRESS_HEADERS=['id','timestamp','email','nisn','nama','id_kelas','id_soal','jenis','level','jawaban','benar','skor','xp','durasi_detik'];
const LM_PETUGAS_HEADERS=['email','nama_guru','literasi','numerasi','status','updated_at'];
function ensureLearningInfrastructure_(){const masterId=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!masterId)throw new Error('MASTER_SIM belum dikonfigurasi.');gatewayEnsureSheet_(masterId,APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL,LM_PETUGAS_HEADERS);gatewayEnsureSheet_(masterId,APP_CONFIG.SHEET.BANK_SOAL,LM_BANK_HEADERS);return masterId}
function readMasterLearningSheet_(sheet){const id=ensureLearningInfrastructure_();return gatewayReadClass_(id,sheet)}
function findSoalPetugasByEmail_(email){if(!email)return null;try{const r=readMasterLearningSheet_(APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL),rows=r.data&&r.data.rows?r.data.rows:[];const u=rows.find(x=>String(x[0]).trim().toLowerCase()===String(email).trim().toLowerCase()&&String(x[4]||'ACTIVE').toUpperCase()!=='INACTIVE');if(!u)return null;return{email:u[0],name:u[1]||u[0],literasi:String(u[2]).toUpperCase()==='TRUE'||String(u[2]).toUpperCase()==='YA',numerasi:String(u[3]).toUpperCase()==='TRUE'||String(u[3]).toUpperCase()==='YA',status:u[4]||'ACTIVE'}}catch(e){return null}}
function getLearningRole_(email){return findSoalPetugasByEmail_(email)?APP_CONFIG.ROLE.PETUGAS_SOAL:null}
function ownerListSoalPetugas(){assertOwner_();ensureLearningInfrastructure_();const r=readMasterLearningSheet_(APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL),rows=r.data&&r.data.rows?r.data.rows:[];return rows.map(x=>({email:x[0],namaGuru:x[1],literasi:truth_(x[2]),numerasi:truth_(x[3]),status:x[4]||'ACTIVE'}))}
function ownerSaveSoalPetugas(data){assertOwner_();const f=data||{},email=String(f.email||'').trim().toLowerCase(),nama=String(f.namaGuru||'').trim();if(!email||!nama)throw new Error('Email guru dan nama guru wajib diisi.');if(!f.literasi&&!f.numerasi)throw new Error('Pilih minimal Literasi atau Numerasi.');const id=ensureLearningInfrastructure_(),r=readMasterLearningSheet_(APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0]).toLowerCase()===email),row=[email,nama,!!f.literasi,!!f.numerasi,String(f.status||'ACTIVE').toUpperCase(),new Date()];if(idx<0)gatewayAppendClass_(id,APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL,row);else{for(let n=rows.length+1;n>=2;n--)if(n===idx+2)gatewayDeleteClass_(id,APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL,n);gatewayAppendClass_(id,APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL,row)}return{ok:true,message:'Petugas soal berhasil disimpan.'}}
function ownerDeleteSoalPetugas(email){assertOwner_();const id=ensureLearningInfrastructure_(),r=readMasterLearningSheet_(APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0]).toLowerCase()===String(email).toLowerCase());if(idx<0)throw new Error('Petugas soal tidak ditemukan.');gatewayDeleteClass_(id,APP_CONFIG.SHEET.MASTER_PETUGAS_SOAL,idx+2);return{ok:true}}
function truth_(v){return v===true||['TRUE','YA','YES','1'].includes(String(v).toUpperCase())}
function teacherCan_(p,jenis){return !!p&&String(p.status).toUpperCase()!=='INACTIVE'&&((jenis===LM_TYPES.LITERASI&&p.literasi)||(jenis===LM_TYPES.NUMERASI&&p.numerasi))}
function normalizeTarget_(v){return String(v||'ALL').trim().toUpperCase()||'ALL'}
function makeQuestionId_(){return 'SOAL-'+Date.now()+'-'+Math.floor(Math.random()*100000)}
function teacherListQuestions(filter){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email);if(!p)throw new Error('Anda belum ditetapkan sebagai PETUGAS_SOAL.');const f=filter||{},jenis=String(f.jenis||'').toUpperCase();const r=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=r.data&&r.data.rows?r.data.rows:[];return rows.filter(x=>{if(!teacherCan_(p,String(x[1]).toUpperCase()))return false;if(jenis&&String(x[1]).toUpperCase()!==jenis)return false;return String(x[15]).toLowerCase()===String(s.email).toLowerCase()}).map(questionPublic_)}
function teacherSaveQuestion(data){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email),d=data||{},jenis=String(d.jenis||'').toUpperCase(),level=Number(d.level);if(!teacherCan_(p,jenis))throw new Error('Anda tidak memiliki izin membuat soal '+jenis+'.');if(!LM_TYPES[jenis])throw new Error('Jenis soal tidak valid.');if(!LM_LEVELS.includes(level))throw new Error('Level soal harus 1 sampai 5.');if(!d.materi||!d.pertanyaan||!d.jawaban)throw new Error('Materi, pertanyaan, dan jawaban wajib diisi.');const tipe=String(d.tipeSoal||'PG').toUpperCase();if(!['PG','BENAR_SALAH'].includes(tipe))throw new Error('V1 hanya mendukung Pilihan Ganda dan Benar/Salah.');const id=String(d.idSoal||makeQuestionId_()),now=new Date(),row=[id,jenis,level,normalizeTarget_(d.targetKelas),d.materi,d.indikator||'',d.stimulus||'',d.pertanyaan,tipe,d.opsiA||'',d.opsiB||'',d.opsiC||'',d.opsiD||'',d.jawaban,d.pembahasan||'',s.email,p.name,'DRAFT',now,now];const masterId=ensureLearningInfrastructure_(),r=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0])===id);if(idx>=0){if(String(rows[idx][15]).toLowerCase()!==String(s.email).toLowerCase())throw new Error('Soal bukan milik Anda.');gatewayDeleteClass_(masterId,APP_CONFIG.SHEET.BANK_SOAL,idx+2)}gatewayAppendClass_(masterId,APP_CONFIG.SHEET.BANK_SOAL,row);return{ok:true,id,message:'Soal disimpan sebagai DRAFT.'}}
function teacherPublishQuestion(id){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email),masterId=ensureLearningInfrastructure_(),r=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0])===String(id));if(idx<0)throw new Error('Soal tidak ditemukan.');const q=rows[idx];if(String(q[15]).toLowerCase()!==String(s.email).toLowerCase()||!teacherCan_(p,q[1]))throw new Error('Anda tidak memiliki akses ke soal ini.');const row=q.slice();row[17]='ACTIVE';row[19]=new Date();gatewayDeleteClass_(masterId,APP_CONFIG.SHEET.BANK_SOAL,idx+2);gatewayAppendClass_(masterId,APP_CONFIG.SHEET.BANK_SOAL,row);return{ok:true,message:'Soal dipublikasikan.'}}
function teacherDeleteQuestion(id){const s=getSessionInfo(),masterId=ensureLearningInfrastructure_(),r=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0])===String(id));if(idx<0)throw new Error('Soal tidak ditemukan.');if(String(rows[idx][15]).toLowerCase()!==String(s.email).toLowerCase())throw new Error('Soal bukan milik Anda.');gatewayDeleteClass_(masterId,APP_CONFIG.SHEET.BANK_SOAL,idx+2);return{ok:true}}
function questionPublic_(q){return{idSoal:q[0],jenis:q[1],level:Number(q[2]),targetKelas:q[3],materi:q[4],indikator:q[5],stimulus:q[6],pertanyaan:q[7],tipeSoal:q[8],opsiA:q[9],opsiB:q[10],opsiC:q[11],opsiD:q[12],jawaban:q[13],pembahasan:q[14],status:q[17],pembuatEmail:q[15],pembuatNama:q[16]}}
function getLearningDashboard(){const s=getSessionInfo();if(s.role!=='SISWA')return{ok:true,role:s.role};const k=findKelasForSession_(s);if(!k)throw new Error('Kelas siswa belum terdaftar.');const bank=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=bank.data&&bank.data.rows?bank.data.rows:[],active=rows.filter(q=>String(q[17]).toUpperCase()==='ACTIVE'&&(normalizeTarget_(q[3])==='ALL'||normalizeTarget_(q[3])===normalizeTarget_(k.idKelas)));const trx=ensureLearningProgressSheet_(k.spreadsheetId),tr=trx.data&&trx.data.rows?trx.data.rows:[];const own=tr.filter(x=>String(x[2]).toLowerCase()===String(s.email).toLowerCase()),correct=own.filter(x=>truth_(x[10])).length,xp=own.reduce((a,x)=>a+Number(x[12]||0),0),byType={LITERASI:{correct:0,total:0},NUMERASI:{correct:0,total:0}};own.forEach(x=>{const t=String(x[7]).toUpperCase();if(byType[t]){byType[t].total++;if(truth_(x[10]))byType[t].correct++}});return{ok:true,role:s.role,xp,correct,total:own.length,streak:calcStreak_(own),badge:badgeFor_(correct),byType,available:LM_TYPES_LIST_().map(j=>({jenis:j,levels:LM_LEVELS.map(l=>({level:l,soal:active.filter(q=>String(q[1]).toUpperCase()===j&&Number(q[2])===l).length,unlocked:l===1||correct>=((l-1)*5)}))}))}}
function LM_TYPES_LIST_(){return[LM_TYPES.LITERASI,LM_TYPES.NUMERASI]}
function startLearningChallenge(jenis,level,count){const s=getSessionInfo(),k=findKelasForSession_(s);if(s.role!=='SISWA')throw new Error('Hanya siswa yang dapat mengerjakan latihan.');jenis=String(jenis||'').toUpperCase();level=Number(level);if(!LM_TYPES_LIST_().includes(jenis)||!LM_LEVELS.includes(level))throw new Error('Tantangan tidak valid.');const dash=getLearningDashboard();const unlocked=dash.available.find(x=>x.jenis===jenis)?.levels.find(x=>x.level===level)?.unlocked;if(!unlocked)throw new Error('Level ini masih terkunci.');const bank=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=bank.data&&bank.data.rows?bank.data.rows:[];let qs=rows.filter(q=>String(q[17]).toUpperCase()==='ACTIVE'&&String(q[1]).toUpperCase()===jenis&&Number(q[2])===level&&(normalizeTarget_(q[3])==='ALL'||normalizeTarget_(q[3])===normalizeTarget_(k.idKelas)));qs=shuffle_(qs).slice(0,Math.min(Math.max(Number(count)||5,1),10));if(!qs.length)throw new Error('Belum ada soal aktif untuk tantangan ini.');return{ok:true,jenis,level,questions:qs.map(q=>({idSoal:q[0],materi:q[4],stimulus:q[6],pertanyaan:q[7],tipeSoal:q[8],opsiA:q[9],opsiB:q[10],opsiC:q[11],opsiD:q[12]}))}}
function submitLearningChallenge(payload){const s=getSessionInfo(),k=findKelasForSession_(s);if(s.role!=='SISWA')throw new Error('Hanya siswa yang dapat mengirim jawaban.');if(!k)throw new Error('Kelas siswa belum terdaftar.');const answers=Array.isArray(payload?.answers)?payload.answers:[];if(!answers.length)throw new Error('Belum ada jawaban.');const bank=readMasterLearningSheet_(APP_CONFIG.SHEET.BANK_SOAL),rows=bank.data&&bank.data.rows?bank.data.rows:[],now=new Date(),trx=[];let benar=0,xp=0;answers.forEach(a=>{const q=rows.find(x=>String(x[0])===String(a.idSoal));if(!q||String(q[17]).toUpperCase()!=='ACTIVE')return;const ok=String(a.jawaban||'').trim().toUpperCase()===String(q[13]||'').trim().toUpperCase();const lv=Number(q[2]||1),gain=ok?lv*10:0;if(ok)benar++;xp+=gain;trx.push(['LM-'+Date.now()+'-'+Math.floor(Math.random()*100000),now,s.email,s.nisn||'',s.name||'',k.idKelas,q[0],q[1],lv,a.jawaban||'',ok,gain,gain,Number(a.durasiDetik||0)])});if(trx.length){ensureLearningProgressSheet_(k.spreadsheetId);trx.forEach(r=>gatewayAppendClass_(k.spreadsheetId,APP_CONFIG.SHEET.LATIHAN_SOAL,r))}return{ok:true,total:trx.length,benar,xp,skor:trx.length?Math.round(benar/trx.length*100):0,badge:badgeFor_(getLearningDashboard().correct+benar)}}
function ensureLearningProgressSheet_(spreadsheetId){gatewayEnsureSheet_(spreadsheetId,APP_CONFIG.SHEET.LATIHAN_SOAL,LM_PROGRESS_HEADERS);return gatewayReadClass_(spreadsheetId,APP_CONFIG.SHEET.LATIHAN_SOAL)}
function shuffle_(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function calcStreak_(rows){const days=new Set(rows.map(x=>Utilities.formatDate(new Date(x[1]),APP_CONFIG.TIMEZONE,'yyyy-MM-dd'))),d=new Date(),today=Utilities.formatDate(d,APP_CONFIG.TIMEZONE,'yyyy-MM-dd');let n=0;for(let i=0;i<60;i++){const k=new Date(d);k.setDate(k.getDate()-i);const key=Utilities.formatDate(k,APP_CONFIG.TIMEZONE,'yyyy-MM-dd');if(days.has(key))n++;else if(i>0)break}return n}
function badgeFor_(correct){if(correct>=100)return'👑 Master Tantangan';if(correct>=50)return'🔥 Penakluk Soal';if(correct>=25)return'⚡ Penantang';if(correct>=10)return'🌿 Penjelajah';if(correct>=5)return'🌱 Pemula Aktif';return'🎯 Mulai Tantangan'}
