/** MASTER DATA GURU / MAPEL / PENUGASAN KELAS — OWNER only. Referensi siswa memakai snapshot/Gateway. */
const MASTER_DATA_SHEETS_ = Object.freeze({GURU:'MASTER_GURU',MAPEL:'MASTER_MAPEL',GURU_KELAS:'GURU_KELAS'});
const MASTER_REF_PROP_='SM_MASTER_REF_V1';
function ensureMasterDataSheets_(){assertOwner_();const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID));const defs=[[MASTER_DATA_SHEETS_.GURU,['id_guru','nip','nama_guru','email','status','created_at','updated_at']],[MASTER_DATA_SHEETS_.MAPEL,['kode_mapel','nama_mapel','kelompok','status','created_at','updated_at']],[MASTER_DATA_SHEETS_.GURU_KELAS,['id_guru','id_kelas','kode_mapel','status','created_at','updated_at']]];defs.forEach(([name,headers])=>{let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(headers);else if(String(sh.getRange(1,1).getValue())!==headers[0])sh.insertRows(1,1).getRange(1,1,1,headers.length).setValues([headers])});return true}
function refreshMasterReferenceSnapshot_(){assertOwner_();const masterId=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!masterId)return false;const ss=SpreadsheetApp.openById(masterId);const read=(name)=>{const sh=ss.getSheetByName(name);return sh&&sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).getValues():[]};const guru=read(MASTER_DATA_SHEETS_.GURU).filter(r=>r[0]&&String(r[4]).toUpperCase()==='ACTIVE').map(r=>({idGuru:r[0],nip:r[1],namaGuru:r[2],email:r[3]}));const mapel=read(MASTER_DATA_SHEETS_.MAPEL).filter(r=>r[0]&&String(r[3]).toUpperCase()==='ACTIVE').map(r=>({kodeMapel:r[0],namaMapel:r[1],kelompok:r[2]}));PropertiesService.getScriptProperties().setProperty(MASTER_REF_PROP_,JSON.stringify({guru,mapel,updatedAt:new Date().toISOString()}));return true}
function getMasterReferenceSnapshot_(){try{const raw=PropertiesService.getScriptProperties().getProperty(MASTER_REF_PROP_);return raw?JSON.parse(raw):null}catch(e){return null}}
function getMasterData(){assertOwner_();ensureMasterDataSheets_();const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID));const read=name=>ss.getSheetByName(name).getDataRange().getValues().slice(1);const out={guru:read(MASTER_DATA_SHEETS_.GURU).filter(r=>r[0]).map(r=>({idGuru:r[0],nip:r[1],namaGuru:r[2],email:r[3],status:r[4]})),mapel:read(MASTER_DATA_SHEETS_.MAPEL).filter(r=>r[0]).map(r=>({kodeMapel:r[0],namaMapel:r[1],kelompok:r[2],status:r[3]})),guruKelas:read(MASTER_DATA_SHEETS_.GURU_KELAS).filter(r=>r[0]).map(r=>({idGuru:r[0],idKelas:r[1],kodeMapel:r[2],status:r[3]})),kelas:listKelas_()};try{refreshMasterReferenceSnapshot_()}catch(e){}return out}
function saveMasterGuru(data){assertOwner_();ensureMasterDataSheets_();data=data||{};const nip=String(data.nip||'').trim(),nama=String(data.namaGuru||'').trim(),email=String(data.email||'').trim().toLowerCase();if(!nip||!nama)throw new Error('NIP dan nama guru wajib diisi.');const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.GURU),rows=sh.getDataRange().getValues();let idx=rows.findIndex((r,i)=>i>0&&(String(r[0])===String(data.idGuru||'')||String(r[1])===nip));const id=idx>0?String(rows[idx][0]):'GURU-'+Utilities.getUuid().slice(0,8).toUpperCase(),now=new Date(),row=[id,nip,nama,email,'ACTIVE',idx>0?rows[idx][5]:now,now];if(idx>0)sh.getRange(idx+1,1,1,row.length).setValues([row]);else sh.appendRow(row);refreshMasterReferenceSnapshot_();return{ok:true,message:'Master guru berhasil disimpan.',idGuru:id}}
function deleteMasterGuru(idGuru){assertOwner_();ensureMasterDataSheets_();const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.GURU),rows=sh.getDataRange().getValues(),idx=rows.findIndex((r,i)=>i>0&&String(r[0])===String(idGuru));if(idx<1)throw new Error('Guru tidak ditemukan.');sh.deleteRow(idx+1);const map=ss.getSheetByName(MASTER_DATA_SHEETS_.GURU_KELAS),mr=map.getDataRange().getValues();for(let i=mr.length-1;i>0;i--)if(String(mr[i][0])===String(idGuru))map.deleteRow(i+1);refreshMasterReferenceSnapshot_();return{ok:true,message:'Guru dan penugasan kelasnya berhasil dihapus.'}}
function saveMasterMapel(data){assertOwner_();ensureMasterDataSheets_();data=data||{};const kode=String(data.kodeMapel||'').trim().toUpperCase(),nama=String(data.namaMapel||'').trim(),kelompok=String(data.kelompok||'').trim();if(!kode||!nama)throw new Error('Kode dan nama mata pelajaran wajib diisi.');const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.MAPEL),rows=sh.getDataRange().getValues(),idx=rows.findIndex((r,i)=>i>0&&String(r[0]).toUpperCase()===kode),now=new Date(),row=[kode,nama,kelompok,'ACTIVE',idx>0?rows[idx][4]:now,now];if(idx>0)sh.getRange(idx+1,1,1,row.length).setValues([row]);else sh.appendRow(row);refreshMasterReferenceSnapshot_();return{ok:true,message:'Master mata pelajaran berhasil disimpan.'}}
function deleteMasterMapel(kode){assertOwner_();ensureMasterDataSheets_();const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.MAPEL),rows=sh.getDataRange().getValues(),idx=rows.findIndex((r,i)=>i>0&&String(r[0]).toUpperCase()===String(kode).toUpperCase());if(idx<1)throw new Error('Mapel tidak ditemukan.');sh.deleteRow(idx+1);refreshMasterReferenceSnapshot_();return{ok:true}}
function saveGuruKelas(data){assertOwner_();ensureMasterDataSheets_();data=data||{};const idGuru=String(data.idGuru||'').trim(),idKelas=String(data.idKelas||'').trim(),kode=String(data.kodeMapel||'').trim().toUpperCase();if(!idGuru||!idKelas||!kode)throw new Error('Guru, kelas, dan mapel wajib dipilih.');const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.GURU_KELAS),rows=sh.getDataRange().getValues(),duplicate=rows.some((r,i)=>i>0&&String(r[0])===idGuru&&String(r[1])===idKelas&&String(r[2])===kode&&String(r[3])==='ACTIVE');if(duplicate)throw new Error('Penugasan guru, kelas, dan mapel tersebut sudah ada.');const now=new Date();sh.appendRow([idGuru,idKelas,kode,'ACTIVE',now,now]);return{ok:true,message:'Penugasan guru ke kelas berhasil disimpan.'}}
function deleteGuruKelas(idGuru,idKelas,kode){assertOwner_();ensureMasterDataSheets_();const ss=SpreadsheetApp.openById(PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID)),sh=ss.getSheetByName(MASTER_DATA_SHEETS_.GURU_KELAS),rows=sh.getDataRange().getValues(),idx=rows.findIndex((r,i)=>i>0&&String(r[0])===String(idGuru)&&String(r[1])===String(idKelas)&&String(r[2])===String(kode));if(idx<1)throw new Error('Penugasan tidak ditemukan.');sh.deleteRow(idx+1);return{ok:true}}
/** SISWA: tidak pernah SpreadsheetApp.openById(MASTER). Jika snapshot belum ada, ambil lewat Gateway yang execute-as OWNER. */
function getStudentMasterReference_(){const snap=getMasterReferenceSnapshot_();if(snap&&Array.isArray(snap.guru)&&Array.isArray(snap.mapel))return snap;const masterId=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!masterId)throw new Error('Referensi Master belum dikonfigurasi OWNER.');const result=gatewayGetMasterReference_(masterId),data=result&&result.data?result.data:{};const guru=Array.isArray(data.guru)?data.guru:[],mapel=Array.isArray(data.mapel)?data.mapel:[];if(!guru.length&&!mapel.length)throw new Error('Referensi Guru/Mata Pelajaran belum tersedia. Jalankan inisialisasi MASTER oleh OWNER.');const next={guru,mapel,updatedAt:data.updatedAt||new Date().toISOString()};try{PropertiesService.getScriptProperties().setProperty(MASTER_REF_PROP_,JSON.stringify(next))}catch(e){}return next}
function getGuruReference(){return getStudentMasterReference_().guru}
function getMapelReference(){return getStudentMasterReference_().mapel}
function refreshMasterReferenceSnapshot(){assertOwner_();return{ok:refreshMasterReferenceSnapshot_(),message:'Referensi Guru dan Mata Pelajaran berhasil diperbarui.'}}
