/** SATRIA MUDA V1.4 — master data pusat. */
const MASTER_KELAS_HEADERS=['id_kelas','nama_kelas','spreadsheet_id','folder_id','admin_email','status','updated_at'];
const MASTER_MODUL_HEADERS=['id_modul','jenis','nama_modul','deskripsi','target_kelas','status','pembuat_email','pembuat_nama','created_at','updated_at'];
function ensureCentralMasters_(){const id=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!id)throw new Error('ID Spreadsheet MASTER SATRIA MUDA belum dikonfigurasi.');const cache=CacheService.getScriptCache(),key='SM_MASTER_READY_'+id;try{if(cache.get(key))return id}catch(e){}gatewayEnsureSheet_(id,APP_CONFIG.SHEET.MASTER_KELAS,MASTER_KELAS_HEADERS);gatewayEnsureSheet_(id,APP_CONFIG.SHEET.MASTER_MODUL,MASTER_MODUL_HEADERS);migrateLegacyMasterKelas_();try{cache.put(key,'1',60)}catch(e){}return id}
function migrateLegacyMasterKelas_(){const id=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!id)return;const d=gatewayReadClass_(id,APP_CONFIG.SHEET.MASTER_KELAS),dst=d.data&&d.data.rows?d.data.rows:[];if(dst.length)return;try{const r=gatewayReadClass_(id,APP_CONFIG.SHEET.MASTER_SIM),rows=r.data&&r.data.rows?r.data.rows:[];rows.filter(x=>x[0]).forEach(x=>gatewayAppendClass_(id,APP_CONFIG.SHEET.MASTER_KELAS,[x[0],x[1],x[2],x[3],x[4],x[5]||'ACTIVE',x[6]||new Date()]))}catch(e){}}
function getMasterKelas(){const id=ensureCentralMasters_(),cache=CacheService.getScriptCache(),key='SM_MASTER_KELAS_'+id;try{const c=cache.get(key);if(c)return JSON.parse(c)}catch(e){}const r=gatewayReadClass_(id,APP_CONFIG.SHEET.MASTER_KELAS),rows=r.data&&r.data.rows?r.data.rows:[],out=rows.filter(x=>x[0]&&String(x[5]||'ACTIVE').toUpperCase()!=='INACTIVE').map(x=>({idKelas:String(x[0]),namaKelas:String(x[1]||x[0]),spreadsheetId:String(x[2]||''),folderId:String(x[3]||''),adminEmail:String(x[4]||''),status:String(x[5]||'ACTIVE')}));try{cache.put(key,JSON.stringify(out),30)}catch(e){}return out}
function getMasterKelasForLearning(){const s=getSessionInfo();if(![APP_CONFIG.ROLE.PETUGAS_SOAL,APP_CONFIG.ROLE.OWNER].includes(s.role))throw new Error('Akses master kelas tidak diizinkan.');return getMasterKelas()}
function ownerListMasterKelas(){assertOwner_();return getMasterKelas()}
function normalizeLearningTargetValue_(v){const t=String(v==null?'':v).trim().toUpperCase().replace(/\s+/g,' ');const compact=t.replace(/[\s_\-\/]/g,'');if(!t)return'ALL';if(compact==='ALL'||compact==='SEMUA'||compact==='ALLKELAS'||compact==='SEMUA KELAS'.replace(/\s/g,'')||compact==='SEMUAALLKELAS')return'ALL';return t}
function getMasterModul_(includeInactive){const id=ensureCentralMasters_(),cache=CacheService.getScriptCache(),key='SM_MASTER_MODUL_'+(includeInactive?'ALL':'ACTIVE');try{const c=cache.get(key);if(c)return JSON.parse(c)}catch(e){}const r=gatewayReadClass_(id,APP_CONFIG.SHEET.MASTER_MODUL),rows=r.data&&r.data.rows?r.data.rows:[],out=rows.filter(x=>x[0]&&(includeInactive||String(x[5]||'ACTIVE').toUpperCase()==='ACTIVE')).map(x=>({idModul:String(x[0]),jenis:String(x[1]).toUpperCase(),namaModul:String(x[2]),deskripsi:String(x[3]||''),targetKelas:normalizeLearningTargetValue_(x[4]),status:String(x[5]||'ACTIVE').toUpperCase(),pembuatEmail:String(x[6]||''),pembuatNama:String(x[7]||'')}));try{cache.put(key,JSON.stringify(out),30)}catch(e){}return out}
function getActiveLearningModulesForStudent(){const s=getSessionInfo(),k=findKelasForSession_(s);if(!k)throw new Error('Kelas siswa belum terdaftar.');const kelas=String(k.idKelas||'').trim().toUpperCase();return getMasterModul_(false).filter(m=>normalizeLearningTargetValue_(m.targetKelas)==='ALL'||normalizeLearningTargetValue_(m.targetKelas)===kelas)}
function teacherListLearningModules(){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email);if(!p)throw new Error('Anda belum ditetapkan sebagai PETUGAS_SOAL.');return getMasterModul_(true).filter(m=>teacherCan_(p,m.jenis)).sort((a,b)=>a.jenis.localeCompare(b.jenis)||a.namaModul.localeCompare(b.namaModul))}
function teacherSaveLearningModule(data){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email),f=data||{},jenis=String(f.jenis||'').toUpperCase();if(!teacherCan_(p,jenis))throw new Error('Anda tidak memiliki izin membuat modul '+jenis+'.');const nama=String(f.namaModul||'').trim();if(!nama)throw new Error('Nama modul wajib diisi.');const idModul=String(f.idModul||('MOD-'+jenis+'-'+Date.now())),target=normalizeLearningTargetValue_(f.targetKelas||'ALL');if(target!=='ALL'&&!getMasterKelas().some(k=>String(k.idKelas).toUpperCase()===target))throw new Error('Target kelas tidak ditemukan di MASTER_KELAS.');const now=new Date(),row=[idModul,jenis,nama,String(f.deskripsi||''),target,String(f.status||'ACTIVE').toUpperCase(),s.email,p.name,now,now],mid=ensureCentralMasters_(),r=gatewayReadClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0])===idModul);if(idx>=0){if(String(rows[idx][6]).toLowerCase()!==s.email.toLowerCase())throw new Error('Modul bukan milik Anda.');gatewayDeleteClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL,idx+2)}gatewayAppendClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL,row);CacheService.getScriptCache().remove('SM_MASTER_MODUL_ACTIVE');CacheService.getScriptCache().remove('SM_MASTER_MODUL_ALL');return{ok:true,idModul,message:'Modul berhasil disimpan.'}}
function teacherSetLearningModuleStatus(idModul,status){const s=getSessionInfo(),p=findSoalPetugasByEmail_(s.email),mid=ensureCentralMasters_(),r=gatewayReadClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL),rows=r.data&&r.data.rows?r.data.rows:[],idx=rows.findIndex(x=>String(x[0])===String(idModul));if(idx<0)throw new Error('Modul tidak ditemukan.');if(String(rows[idx][6]).toLowerCase()!==s.email.toLowerCase()||!teacherCan_(p,String(rows[idx][1]).toUpperCase()))throw new Error('Anda tidak memiliki akses ke modul ini.');const row=rows[idx].slice();row[5]=String(status||'INACTIVE').toUpperCase();row[9]=new Date();gatewayDeleteClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL,idx+2);gatewayAppendClass_(mid,APP_CONFIG.SHEET.MASTER_MODUL,row);CacheService.getScriptCache().remove('SM_MASTER_MODUL_ACTIVE');CacheService.getScriptCache().remove('SM_MASTER_MODUL_ALL');return{ok:true,status:row[5]}}
function ownerListLearningModules(){assertOwner_();return getMasterModul_(true)}
