/** OWNER setup: semua nilai penting diisi melalui frontend. */
function ownerSaveConfig(form){assertOwner_();form=form||{};const masterId=String(form.masterSimId||'').trim(),gatewayUrl=String(form.gatewayUrl||'').trim(),gatewayToken=String(form.gatewayToken||'').trim();if(!masterId)throw new Error('ID Spreadsheet MASTER SATRIA MUDA wajib diisi.');SpreadsheetApp.openById(masterId);if(gatewayUrl&&!gatewayToken)throw new Error('Gateway URL diisi maka Token Gateway juga wajib diisi.');PropertiesService.getScriptProperties().setProperties({MASTER_SIM_ID:masterId,GATEWAY_URL:gatewayUrl,GATEWAY_TOKEN:gatewayToken,SETUP_OWNER_EMAIL:APP_CONFIG.OWNER_EMAIL},true);ensureMasterSim_();ensureCentralMasters_();try{refreshMasterReferenceSnapshot_()}catch(e){}if(gatewayUrl&&gatewayToken)configureGatewayToken_(gatewayUrl,gatewayToken);return{ok:true,message:'Konfigurasi OWNER berhasil disimpan. MASTER SATRIA MUDA dan Gateway siap digunakan.',setup:getSetupStatus_(true)}}
function configureGatewayToken_(url,token){const res=UrlFetchApp.fetch(url,{method:'post',contentType:'application/json',payload:JSON.stringify({action:'SET_GATEWAY_TOKEN',ownerEmail:APP_CONFIG.OWNER_EMAIL,newToken:token}),muteHttpExceptions:true,followRedirects:true});let data;try{data=JSON.parse(res.getContentText()||'')}catch(e){throw new Error('Gateway tidak mengembalikan JSON saat konfigurasi token. HTTP '+res.getResponseCode())}if(!data.ok)throw new Error(data.message||'Gateway menolak konfigurasi token.')}
function ownerInitializeMaster(){assertOwner_();ensureMasterSim_();ensureCentralMasters_();try{refreshMasterReferenceSnapshot_()}catch(e){}return{ok:true,message:'MASTER SATRIA MUDA berhasil dibuat/dilengkapi.',setup:getSetupStatus_(true)}}
function ownerSaveKelas(form){assertOwner_();form=form||{};return ownerSaveMasterKelas(form)}
function ownerPrepareAllClasses(){assertOwner_();const kelas=getMasterKelas();let count=0;kelas.forEach(k=>{ensureKelasSpreadsheet_(k.spreadsheetId,k.idKelas,k.adminEmail);count++});return{ok:true,message:count+' kelas berhasil disiapkan untuk Gateway dan modul siswa.'}}
function assertOwner_(){const email=String(Session.getActiveUser().getEmail()||'').toLowerCase();if(email!==APP_CONFIG.OWNER_EMAIL.toLowerCase())throw new Error('Akses OWNER diperlukan.')}
function getMasterSheet_(){const id=PropertiesService.getScriptProperties().getProperty(APP_CONFIG.PROP.MASTER_SIM_ID);if(!id)throw new Error('MASTER SATRIA MUDA belum dikonfigurasi.');const ss=SpreadsheetApp.openById(id);return ss.getSheetByName(APP_CONFIG.SHEET.MASTER_SIM)||ss.insertSheet(APP_CONFIG.SHEET.MASTER_SIM)}
function ensureMasterSim_(){const sh=getMasterSheet_();if(sh.getLastRow()===0)sh.appendRow(['id_kelas','nama_kelas','spreadsheet_id','folder_id','admin_email','status','updated_at']);else if(String(sh.getRange(1,1).getValue())!=='id_kelas')sh.insertRows(1,1).getRange(1,1,1,7).setValues([['id_kelas','nama_kelas','spreadsheet_id','folder_id','admin_email','status','updated_at']])}
function ensureKelasSpreadsheet_(id,kelasId,adminEmail){const ss=SpreadsheetApp.openById(id);let users=ss.getSheetByName(APP_CONFIG.SHEET.USERS)||ss.insertSheet(APP_CONFIG.SHEET.USERS);if(users.getLastRow()===0)users.appendRow(['id_user','nisn','nama','email','role','status','id_kelas']);let agenda=ss.getSheetByName(APP_CONFIG.SHEET.AGENDA_BELAJAR)||ss.insertSheet(APP_CONFIG.SHEET.AGENDA_BELAJAR);const newAgendaHeaders=['id','timestamp','email','nisn','nama','id_kelas','tanggal','namaGuru','mataPelajaran','materi','tujuanBelajar','kegiatan','refleksi'];if(agenda.getLastRow()===0)agenda.appendRow(newAgendaHeaders);else{const h=agenda.getRange(1,1,1,Math.max(agenda.getLastColumn(),newAgendaHeaders.length)).getValues()[0];const oldAgenda=String(h[7]||'')==='mataPelajaran'&&String(h[8]||'')==='materi';if(oldAgenda){if(agenda.getLastRow()===1){agenda.clear();agenda.appendRow(newAgendaHeaders)}else{agenda.insertColumnAfter(7);agenda.getRange(1,1,1,newAgendaHeaders.length).setValues([newAgendaHeaders])}}else if(String(h[7]||'')!=='namaGuru'&&agenda.getLastRow()===1){agenda.getRange(1,1,1,newAgendaHeaders.length).setValues([newAgendaHeaders])}}ensureAllSiswaModuleSheets_(id);const rows=users.getDataRange().getValues(),email=String(adminEmail).toLowerCase();if(!rows.slice(1).some(r=>String(r[3]).toLowerCase()===email))users.appendRow(['ADMIN_'+kelasId,'',adminEmail,adminEmail,'ADMIN_KELAS','ACTIVE',kelasId])}
