/** SATRIA MUDA — 8 modul aktivitas siswa; akses data siswa melalui Write Gateway. */
const SISWA_MODULES=Object.freeze({
 AGENDA_BELAJAR:{nama:'Agenda Belajar',icon:'📚',sheet:'TRX_AGENDA_BELAJAR',fields:[['tanggal','Tanggal','date'],['namaGuru','Nama Guru','selectGuru'],['mataPelajaran','Mata Pelajaran','selectMapel'],['materi','Materi','text'],['tujuanBelajar','Tujuan Belajar','textarea'],['kegiatan','Kegiatan Belajar','textarea'],['refleksi','Refleksi','textarea']]},
 TUJUHKAIH:{nama:'Kegiatan 7KAIH',icon:'🌱',sheet:'TRX_7KAIH',fields:[['tanggal','Tanggal','date'],['kegiatan','Ringkasan Pembiasaan','text'],['kategori','Kategori','text'],['uraian','Cerita/Bukti Pembiasaan','textarea'],['nilaiKarakter','Nilai/Karakter yang Terasa','text'],['refleksi','Refleksi Hari Ini','textarea'],['bangunPagi','Bangun Pagi','habit'],['beribadah','Beribadah','habit'],['berolahraga','Berolahraga','habit'],['makanSehat','Makan Sehat dan Bergizi','habit'],['gemarBelajar','Gemar Belajar','habit'],['bermasyarakat','Bermasyarakat','habit'],['tidurCepat','Tidur Cepat','habit'],['skorHarian','Skor Kebiasaan','text'],['persentaseKebiasaan','Persentase Kebiasaan','text'],['targetBesok','Target Kebiasaan Besok','textarea']]},
 BELAJAR_MANDIRI:{nama:'Kegiatan Belajar Mandiri',icon:'🧠',sheet:'TRX_BELAJAR_MANDIRI',fields:[['tanggal','Tanggal','date'],['mataPelajaran','Mata Pelajaran','text'],['materi','Materi','text'],['sumberBelajar','Sumber Belajar','text'],['durasi','Durasi Belajar','text'],['hasilBelajar','Hasil Belajar','textarea'],['refleksi','Refleksi','textarea']]},
 JURNAL_REFLEKSI:{nama:'Jurnal/Refleksi Belajar',icon:'📝',sheet:'TRX_JURNAL_REFLEKSI',fields:[['tanggal','Tanggal','date'],['mataPelajaran','Mata Pelajaran','text'],['halDipelajari','Hal yang Dipelajari','textarea'],['kesulitan','Kesulitan/Hambatan','textarea'],['solusi','Solusi/Upaya','textarea'],['rencana','Rencana Perbaikan','textarea']]},
 PRESTASI:{nama:'Prestasi Siswa',icon:'🏆',sheet:'TRX_PRESTASI_SISWA',fields:[['tanggal','Tanggal','date'],['bidang','Bidang Prestasi','text'],['namaPrestasi','Nama Prestasi','text'],['tingkat','Tingkat','text'],['penyelenggara','Penyelenggara','text'],['keterangan','Keterangan','textarea']]},
 LITERASI:{nama:'Kegiatan Literasi',icon:'📖',sheet:'TRX_LITERASI_SISWA',fields:[['tanggal','Tanggal','date'],['jenis','Jenis Literasi','text'],['judul','Judul Buku/Sumber','text'],['penulis','Penulis/Sumber','text'],['ringkasan','Ringkasan','textarea'],['refleksi','Refleksi','textarea']]},
 ORGANISASI:{nama:'Kegiatan Organisasi',icon:'🤝',sheet:'TRX_ORGANISASI_SISWA',fields:[['tanggal','Tanggal','date'],['organisasi','Nama Organisasi','text'],['jabatan','Peran/Jabatan','text'],['kegiatan','Nama Kegiatan','text'],['uraian','Uraian Kegiatan','textarea'],['hasil','Hasil/Refleksi','textarea']]},
 AGENDA_KEGIATAN:{nama:'Agenda/Kegiatan Siswa',icon:'📅',sheet:'TRX_KEGIATAN_SISWA',fields:[['tanggal','Tanggal','date'],['jenis','Jenis Kegiatan','text'],['namaKegiatan','Nama Kegiatan','text'],['tempat','Tempat','text'],['uraian','Uraian Kegiatan','textarea'],['hasil','Hasil/Keterangan','textarea']]}
});
const SISWA_MENU_GROUPS=Object.freeze([{kode:'MULIA',nama:'MULIA',icon:'🌱',items:['TUJUHKAIH','JURNAL_REFLEKSI']},{kode:'BERAKHLAK',nama:'BERAKHLAK',icon:'🤝',items:['ORGANISASI']},{kode:'HEBAT',nama:'HEBAT',icon:'🏆',items:['AGENDA_BELAJAR','BELAJAR_MANDIRI','PRESTASI']},{kode:'BERKARYA',nama:'BERKARYA',icon:'✨',items:['LITERASI','AGENDA_KEGIATAN']}]);
function getSiswaModules(){return Object.keys(SISWA_MODULES).map(k=>({kode:k,nama:SISWA_MODULES[k].nama,icon:SISWA_MODULES[k].icon}))}
function getSiswaMenuGroups(){return SISWA_MENU_GROUPS.map(g=>({kode:g.kode,nama:g.nama,icon:g.icon,items:g.items.map(k=>({kode:k,nama:SISWA_MODULES[k].nama,icon:SISWA_MODULES[k].icon}))}))}
function getModuleConfig(kode){const c=requireModule_(kode);return{kode,nama:c.nama,icon:c.icon,sheet:c.sheet,fields:c.fields}}
function moduleHeaders_(cfg){return['id','timestamp','email','nisn','nama','id_kelas'].concat(cfg.fields.map(f=>f[0]))}
function normalizeModuleHeader_(v){return String(v==null?'':v).toLowerCase().replace(/[^a-z0-9]/g,'')}
function moduleHeaderAliases_(key,label){const aliases=[key,label];const special={nilaiKarakter:['nilaiKarakter','Nilai/Karakter yang Terasa','nilai_karakter'],persentaseKebiasaan:['persentaseKebiasaan','Persentase Kebiasaan','persentase'],skorHarian:['skorHarian','Skor Kebiasaan','skor_harian','skor'],targetBesok:['targetBesok','Target Kebiasaan Besok','target_besok'],bangunPagi:['bangunPagi','Bangun Pagi','bangun_pagi'],beribadah:['beribadah','Beribadah'],berolahraga:['berolahraga','Berolahraga'],makanSehat:['makanSehat','Makan Sehat dan Bergizi','makan_sehat'],gemarBelajar:['gemarBelajar','Gemar Belajar','gemar_belajar'],bermasyarakat:['bermasyarakat','Bermasyarakat'],tidurCepat:['tidurCepat','Tidur Cepat','tidur_cepat'],uraian:['uraian','Cerita/Bukti Pembiasaan','Uraian Kegiatan'],kegiatan:['kegiatan','Ringkasan Pembiasaan','Nama Kegiatan'],kategori:['kategori','Kategori']};return(special[key]||aliases).map(normalizeModuleHeader_)}
function findModuleHeaderIndex_(headers,key,label){const aliases=new Set(moduleHeaderAliases_(key,label));return(headers||[]).findIndex(h=>aliases.has(normalizeModuleHeader_(h)))}
function ensureModuleViaGateway_(spreadsheetId,cfg){gatewayEnsureSheet_(spreadsheetId,cfg.sheet,moduleHeaders_(cfg));const currentResult=gatewayReadClass_(spreadsheetId,cfg.sheet),current=Array.isArray(currentResult.data&&currentResult.data.headers)?currentResult.data.headers:[];const base=['id','timestamp','email','nisn','nama','id_kelas'];const missing=moduleHeaders_(cfg).filter(wanted=>{const key=String(wanted);const f=cfg.fields.find(x=>x[0]===key);const aliases=f?moduleHeaderAliases_(f[0],f[1]):[normalizeModuleHeader_(key)];return !current.some(h=>aliases.includes(normalizeModuleHeader_(h)))});if(missing.length)gatewayEnsureHeaders_(spreadsheetId,cfg.sheet,missing);return gatewayReadClass_(spreadsheetId,cfg.sheet)}
function getSiswaModuleData(kode){const cfg=requireModule_(kode),s=getSessionInfo(),k=findKelasForSession_(s);if(!k)return[];const result=ensureModuleViaGateway_(k.spreadsheetId,cfg),rows=result.data&&result.data.rows?result.data.rows:[],headers=result.data&&Array.isArray(result.data.headers)?result.data.headers:moduleHeaders_(cfg);return rows.map((r,i)=>Object.assign(rowToModule_(cfg,r,headers),{_rowNumber:i+2})).filter(r=>String(r.email).toLowerCase()===String(s.email).toLowerCase())}
function buildModuleRow_(cfg,data,s,k,headers){const d=data||{},base={id:'SM-'+Date.now()+'-'+Math.floor(Math.random()*10000),timestamp:new Date(),email:s.email,nisn:s.nisn||'',nama:s.name||'',id_kelas:k.idKelas};return(headers||moduleHeaders_(cfg)).map(h=>{const n=normalizeModuleHeader_(h);if(n===normalizeModuleHeader_('id'))return base.id;if(n===normalizeModuleHeader_('timestamp'))return base.timestamp;if(n===normalizeModuleHeader_('email'))return base.email;if(n===normalizeModuleHeader_('nisn'))return base.nisn;if(n===normalizeModuleHeader_('nama'))return base.nama;if(n===normalizeModuleHeader_('id_kelas'))return base.id_kelas;for(const f of cfg.fields){if(moduleHeaderAliases_(f[0],f[1]).includes(n))return d[f[0]]==null?'':d[f[0]]}return ''})}
function saveSiswaModule(kode,data){const cfg=requireModule_(kode),s=getSessionInfo(),k=findKelasForSession_(s);if(s.role!=='SISWA')throw new Error('Modul kegiatan siswa hanya dapat diinput oleh akun SISWA.');if(!k)throw new Error('Kelas pengguna belum terdaftar.');const result=ensureModuleViaGateway_(k.spreadsheetId,cfg),headers=result.data&&Array.isArray(result.data.headers)?result.data.headers:moduleHeaders_(cfg),d=data||{},row=buildModuleRow_(cfg,d,s,k,headers),idIndex=findModuleHeaderIndex_(headers,'id','id');gatewayAppendClass_(k.spreadsheetId,cfg.sheet,row);return{ok:true,id:idIndex>-1?row[idIndex]:'',message:cfg.nama+' berhasil disimpan.',headers:headers}}
function deleteSiswaModule(kode,id){const cfg=requireModule_(kode),s=getSessionInfo(),k=findKelasForSession_(s);if(s.role!=='SISWA')throw new Error('Hanya siswa yang dapat menghapus data.');if(!k)throw new Error('Kelas pengguna belum terdaftar.');const result=ensureModuleViaGateway_(k.spreadsheetId,cfg),rows=result.data&&result.data.rows?result.data.rows:[],headers=result.data&&Array.isArray(result.data.headers)?result.data.headers:moduleHeaders_(cfg),idIdx=findModuleHeaderIndex_(headers,'id','id'),emailIdx=findModuleHeaderIndex_(headers,'email','email'),idx=rows.findIndex(r=>String(r[idIdx])===String(id)&&String(r[emailIdx]).toLowerCase()===String(s.email).toLowerCase());if(idx<0)throw new Error('Data tidak ditemukan atau bukan milik Anda.');gatewayDeleteClass_(k.spreadsheetId,cfg.sheet,idx+2);return{ok:true,message:'Data berhasil dihapus.'}}
function getAgendaBelajarReference(){return{guru:getGuruReference().map(x=>({idGuru:x.idGuru,namaGuru:x.namaGuru,nip:x.nip})),mapel:getMapelReference().map(x=>({kodeMapel:x.kodeMapel,namaMapel:x.namaMapel,kelompok:x.kelompok}))}}
function requireModule_(kode){const cfg=SISWA_MODULES[String(kode||'').toUpperCase()];if(!cfg)throw new Error('Modul tidak dikenal: '+kode);return cfg}
function findKelasForSession_(s){return listKelas_().find(k=>String(k.idKelas)===String(s.idKelas))}
function rowToModule_(cfg,r,headers){const o={id:'',timestamp:'',email:'',nisn:'',nama:'',idKelas:''},hs=headers&&headers.length?headers:moduleHeaders_(cfg);hs.forEach((h,i)=>{const n=normalizeModuleHeader_(h),v=r[i];if(n===normalizeModuleHeader_('id'))o.id=v;else if(n===normalizeModuleHeader_('timestamp'))o.timestamp=v;else if(n===normalizeModuleHeader_('email'))o.email=v;else if(n===normalizeModuleHeader_('nisn'))o.nisn=v;else if(n===normalizeModuleHeader_('nama'))o.nama=v;else if(n===normalizeModuleHeader_('id_kelas'))o.idKelas=v;else cfg.fields.forEach(f=>{if(moduleHeaderAliases_(f[0],f[1]).includes(n))o[f[0]]=v})});return o}
function ensureAllSiswaModuleSheets_(spreadsheetId){Object.keys(SISWA_MODULES).forEach(k=>{const cfg=SISWA_MODULES[k];ensureModuleViaGateway_(spreadsheetId,cfg)});return true}
function getDashboardData(){const s=getSessionInfo();if(s.role!=='OWNER'&&s.role!=='ADMIN_KELAS')return{ok:true,scope:'NONE',cards:[]};const cache=CacheService.getScriptCache(),key='SATRIA_MUDA_DASHBOARD_V3';try{const cached=cache.get(key);if(cached)return JSON.parse(cached)}catch(e){}const kelas=listKelas_(),cards=[];Object.keys(SISWA_MODULES).forEach(kode=>{const cfg=SISWA_MODULES[kode],items=[];kelas.forEach(k=>{try{const result=ensureModuleViaGateway_(k.spreadsheetId,cfg),data=result&&result.data?result.data:{},rows=Array.isArray(data.rows)?data.rows:(Array.isArray(data.values)?data.values:[]),headers=Array.isArray(data.headers)?data.headers:moduleHeaders_(cfg);rows.forEach(r=>{if(!r||!Array.isArray(r)||!r[0]||String(r[0]).toLowerCase()==='id')return;const o=rowToModule_(cfg,r,headers);o.idKelas=o.idKelas||k.idKelas;o.namaKelas=k.namaKelas||k.idKelas;items.push(o)})}catch(e){}});items.sort((a,b)=>new Date(b.timestamp||b.tanggal||0)-new Date(a.timestamp||a.tanggal||0));const kelasSet=new Set(items.map(x=>String(x.idKelas||x.namaKelas||'')));cards.push({kode,nama:cfg.nama,icon:cfg.icon,total:items.length,kelasCount:kelasSet.size,rows:items.slice(0,8)})});const out={ok:true,scope:'ALL_CLASSES',role:s.role,updatedAt:new Date().toISOString(),cards};try{cache.put(key,JSON.stringify(out),30)}catch(e){}return out}
